### PR TITLE
Removed unnecessary CSS from homepage

### LINKED ISSUE #3: Remove Unnecessary CSS from Homepage.
Homepage is index.html.
Task is to remove unused css and css tags from files used to display homepage.

### PR DESCRIPTION
**Pull request by DNA5769**
Fixes #3 

I first removed unnecessary CSS from the CSS present inside the `<style>` tag. I also moved some of the CSS present and converted it into bootstrap.

I also removed some unnecessary inline CSS

### CODE REVIEW

**Comment by CyrilMishra** [comment]
> Fixes #3
> 
> I first removed unnecessary CSS from the CSS present inside the `<style>` tag. I also moved some of the CSS present and converted it into bootstrap.
> 
> I also removed some unnecessary inline CSS

Hi , DNA5769
You also have to remove the unnecessary from the css files in static folder, that are being used in Homepage(CSS only).

**Comment by DNA5769** [comment]
Ok sir, I'll work on it

**Comment by DNA5769** [comment]
Sir the thing is that the stylesheets present in the static folder, namely `home.css` and `styles.css` are used in many other pages as well. So I don't think I can remove any CSS looking at the homepage alone (since it might be used in other pages).

**Comment by DNA5769** [comment]
> Hi , DNA5769 You also have to remove the unnecessary from the css files in static folder, that are being used in Homepage(CSS only).

Hello Sir, so I looked into it again and there is only one "css files in static folder, that are being used in Homepage" and that is `styles.css`. However `styles.css` consists Bootstrap code, and since it is a CSS framework which we are importing I dont see how removing unused parts of it, is necessary.

But if that's the task then just let me know and I will work on it.

**Comment by CyrilMishra** [comment]
> > Hi , DNA5769 You also have to remove the unnecessary from the css files in static folder, that are being used in Homepage(CSS only).
> 
> Hello Sir, so I looked into it again and there is only one "css files in static folder, that are being used in Homepage" and that is `styles.css`. However `styles.css` consists Bootstrap code, and since it is a CSS framework which we are importing I dont see how removing unused parts of it, is necessary.
> 
> But if that's the task then just let me know and I will work on it.

The task is to remove redundant css , see carefully there are two folders which consists styles.css , task is to merge that two styles.css . You just have to delete several unnecessary lines of code in css file.

**Comment by DNA5769** [comment]
Oh ok, got it sir

**Comment by DNA5769** [comment]
Hello Sir, 

I tried merging the files you had mentioned `assets/styles.css` and `css/styles.css` but actually they were the same file as they had the same content.

So therefore I reduced the line count of `css/styles.css` from **11768** lines to **1415** lines by removing all the unnecessary CSS rules present in it.

`css/styles.css` was actually being used by 4 HTML files, namely
- `index.html`
- `RatingReview.html`
- `edit_profile_form.html`
- `search_result.html`

So I took all of them into consideration while removing the tags.

Also `assets/styles.css` isn't being used by any file, so I just let it be.

**Comment by DNA5769** [comment]
Should I delete `assets/styles.css` ?

**Comment by CyrilMishra** [comment]
If it is not being used anywhere else then remove it.

**Comment by DNA5769** [comment]
Done Sir

**Pull request merged**
