### PR TITLE
Added profile picture to user model

### LINKED ISSUE #2: Take Profile Picture From User and display above Email ID in profile page.
Currently only User Details is taken from user where no profile picture is taken . 
Task is to take profile picture from user and show it on profile page.

### PR DESCRIPTION
**Pull request by kunal2812**
Fixes #2 

- Added option to upload profile picture during signup

image

- Users can view DP on profile page
image

### CODE REVIEW

**Review by CyrilMishra — CHANGES_REQUESTED** [review]
Fix Error while logging in to the homepage. "string index out of range" 
And do "fetch origin" before fixing this error.(Remember to save your commits)

**Comment by kunal2812** [comment]
> Fix Error while logging in to the homepage. "string index out of range" And do "fetch origin" before fixing this error.(Remember to save your commits)

@CyrilMishra when do you see the mentioned error ? I couldn't replicate the same.

**Comment by CyrilMishra** [comment]
> > Fix Error while logging in to the homepage. "string index out of range" And do "fetch origin" before fixing this error.(Remember to save your commits)
> 
> @CyrilMishra when do you see the mentioned error ? I couldn't replicate the same.

On Homepage while logging in .

**Comment by kunal2812** [comment]
> On Homepage while logging in .

Maybe that was because of some bug that was there in main branch. I have fetched origin and updated the branch, could you please check again if you still see an error ?

**Pull request merged**
