### PR TITLE
generalized navigation bar

### PR DESCRIPTION
**Pull request by prackode**

### CODE REVIEW

**Comment by prackode** [comment]
fixes #7 @CyrilMishra

**Comment by CyrilMishra** [comment]
Fetch the origin and remember to save you commits before. Merging the main branch.
Resolve the Issues and commit again.

**Comment by prackode** [comment]
resolved the issue @CyrilMishra

**Comment by CyrilMishra** [comment]
> resolved the issue @CyrilMishra

Everything is good.
Just a little bit of changes are made by other PR's . So, it is requested to you to adjust you Navbar accordingly.
You can do save your code first and fetch origin and then do the changes accordingly.
And it will be good to be merged.

**Comment by prackode** [comment]
pls check #38 @CyrilMishra

**Comment by CyrilMishra** [comment]
> pls check #38 @CyrilMishra 

Search ajax is not working in your PR, please verify with the latest main branch and do the changes accordingly

**Pull request closed without merging**
