### PR TITLE
Added suggestions below search bar

### LINKED ISSUE #42: Give suggestion below search Bar.
When nothing is typed in search bar give top 5 places names, place and their rating according to the ratings provided.

### PR DESCRIPTION
**Pull request by kunal2812**
Fixes #42 

image

Suggestions are visible only when searchbar is focussed and input is empty

### CODE REVIEW

**Comment by CyrilMishra** [comment]
resolve conflicts and then push.

**Comment by kunal2812** [comment]
Done @CyrilMishra

**Comment by CyrilMishra** [comment]
Give a target to open portfoliomodal of place on the suggested place when clicked on.

**Comment by kunal2812** [comment]
> Give a target to open portfoliomodal of place on the suggested place when clicked on.

Fixed

**Comment by CyrilMishra** [comment]
> > Give a target to open portfoliomodal of place on the suggested place when clicked on.
> 
> Fixed

It is not working, still. 
Also, remember to pull origin first.

**Comment by kunal2812** [comment]
Sorry there was a issue with index of portfolio modals when new places were created, while it worked fine with places that were already in db. Now it is fixed please check @CyrilMishra

**Comment by kunal2812** [comment]
Sorry there was a issue with index of portfolio modals when new places were created, while it worked fine with places that were already in db. 
There was also error with indexing ratings and reviews that was affecting portfolio-modals. Previously indexing was done based on pk but there was issue if the place was deleted and new places were added so indexing has been fixed and consequently this issue is resolved.
Please check @CyrilMishra

**Pull request merged**
