### PR TITLE
Improving messages

### PR DESCRIPTION
**Pull request by eleensmathew**
## Made messages more consistent

Corrected the message after registering,invalid credentails and logging out. Unforu=tunately the javascript for invalid credentials is not getting loaded for some reason.

## Related Issue

Fixes # (https://github.com/ContriHUB/Sheher/issues/60)

### CODE REVIEW

**Comment by eleensmathew** [comment]
Just let me know if i should pull current changes and commit again.

**Comment by kunal2812** [comment]
Message for Invalid Credentials not working as expected.

image

This does not disappear

**Comment by eleensmathew** [comment]
Ya the script tag on that html page is not getting loaded. I'm unable to
figure out why. Invested a lot of time on it too. Would be helpful if you
have any suggestions for the same

**Comment by kunal2812** [comment]
You can add new script and style for specifically this message if existing one is not working on this one

**Comment by eleensmathew** [comment]
Okay let me check that out.

**Comment by eleensmathew** [comment]
Fixed the issue👍

**Comment by kunal2812** [comment]
Can you add same style to "Invalid Credentials" message too ?

**Comment by eleensmathew** [comment]
How about now?

**Comment by kunal2812** [comment]
Everything changed except that message 💀

image

That font you changed was probably applied to all pages. Please test your code properly before submitting for review.

**Comment by kunal2812** [comment]
LGTM

**Comment by eleensmathew** [comment]
Wait is there any issue?

**Comment by kunal2812** [comment]
No. That was a mistake from my end.

**Review by kunal2812 — APPROVED** [review]

**Pull request merged**
